# Generated by Django 4.1.7 on 2023-04-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubowner',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
