# Generated by Django 4.1.7 on 2023-04-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0005_hubowner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
